### PR TITLE
Add cstacksize command

### PR DESCRIPTION
**Pull request by haykam821**
This pull request adds a new command to view the total number of stacks for a given item.

### CODE REVIEW

**Comment by Earthcomputer** [comment]
Just fyi, `/ccalc <n>` already displays the number of stacks and the remainder assuming the item stacks to 64. As for this PR, perhaps the command could have a better name?

**Comment by zax71** [comment]
I think that would be a great idea!, where is a list of commands this mod adds?

**Comment by OneYellowLemon** [comment]
Maybe /cstack

**Comment by zax71** [comment]
i think either have the old one and /stacksize, just /stacksize or all 3

**Comment by Earthcomputer** [comment]
The old one is a general purpose calculator that does maths, this is not a replacement for that. I don't like adding aliases because it encourages 12 year olds to ask "where are my 2 letter commands" like they don't know that tab exists. I'm happy to accept this PR only because it adds the extra functionality of calculating items that don't stack to 64, however I don't like the name /cstacksize, however I can't immediately think of a better name.

**Comment by zax71** [comment]
thx for replying so quick. i think adding the finctionality would be GREAT! but i get what you meen

(ps i'm 12)

**Comment by Earthcomputer** [comment]
Ah, sorry for generalizing, but I'm sure you know the types of players I mean ;)
How about `/ccalcstack`?

**Comment by zax71** [comment]
yes, i do know who you mean and, i think that's a great name for the command, if it gets added soon i'l download the mod to add to my client side mod pack (for personal use).

so i don't download the wrong version of the mod, when will the update come out?

**Comment by Earthcomputer** [comment]
I'll see about releasing a new version today.

**Comment by zax71** [comment]
thank you if you could put a comment on here when you've added it so i get notified, thx for being so quick!

**Comment by Earthcomputer** [comment]
Should be released now.

**Comment by zax71** [comment]
ok, i'll download it!

**Comment by zax71** [comment]
could you add it to the 1.15 version because i play on 1.15 because of optifine

**Comment by Earthcomputer** [comment]
No. I don't maintain old versions. Also there are alternatives to optifine nowadays, like Sodium.

**Comment by zax71** [comment]
oh, then i won't use it untill optifine updates sorry

**Comment by Earthcomputer** [comment]
Sorry but optifine will be incompatible with 1.16 fabric, as we're dropping support for it. It's ancient, not even as effective as Sodium, and causes tons of mod incompatibilities which are hard to fix because the owner is a dick and doesn't care about compatibility.

**Comment by zax71** [comment]
ok, i'll try sodium sometime

**Comment by zax71** [comment]
can you give me a download link to sodium, i can't find a .jar file

**Comment by seanguy244** [comment]
https://github.com/jellysquid3/sodium-fabric repo for the mod

**Comment by zax71** [comment]
Where’s the .jar tho? I can’t find it can you give me a more direct link

**Comment by Earthcomputer** [comment]
Google "fabric sodium download" second result for me.

**Comment by zax71** [comment]
It’s just the github page that shows up can you give me a link to the downloads page?

**Comment by Earthcomputer** [comment]
It's on curseforge. Now this has got very off topic.

**Pull request merged**
