### PR TITLE
Updated Indonesian Translate

### PR DESCRIPTION
**Pull request by barraIhsan**
Please merge it before the next release, to make sure that the translation is up to date.

### CODE REVIEW

**Comment by barraIhsan** [comment]
This is the old branch, I should have created a new branch instead. Ignore the first 10 commits. Its just the previous one

**Comment by xpple** [comment]
> This is the old branch, I should have created a new branch instead. Ignore the first 10 commits. Its just the previous one

Don’t worry - it happens to the best (me).

**Comment by xpple** [comment]
It seems you have changed the indentation of the entire file, could you revert that?

**Comment by barraIhsan** [comment]
Oh yeah! I forgot that my editor does that. I will fix it rn

**Comment by barraIhsan** [comment]
Disclaimer: Some of my commits is not verified because there is no option for signing commit in the new `github.dev` yet

**Pull request merged**
