### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by GodGun968**

### CODE REVIEW

**Comment by GodGun968** [comment]
@Earthcomputer Hi, Can you merge this

**Comment by Earthcomputer** [comment]
> Hi, Can you merge this

Hi, I normally merge translation PRs before I make a new release.

Also, looks like you have some merge conflicts to resolve.

**Comment by GodGun968** [comment]
The language file is updated .... I need to re-translate and then resolve the conflict

**Comment by GodGun968** [comment]
Okay, now you can merge it whenever you want.

**Review by Earthcomputer — APPROVED** [review]

**Pull request merged**
