### PR TITLE
Fix border outlines

### LINKED ISSUE #221: `/cglow area` highlighted box is wrong
The highlighted area of blocks is wrong!
for the `<from>` coordinates is off by `+Y+Z`
for the `<to>` coordinates its off by `+X`

### PR DESCRIPTION
**Pull request by xpple**
Closes #221

### CODE REVIEW

**Review by Earthcomputer — COMMENTED** [review]
Hmm, is there a better way of doing this, maybe with `Math.min` and `Math.max`?

**Comment by xpple** [comment]
Yes, but it's slightly slower since the amount of if-statements doubles.

**Comment by Earthcomputer** [comment]
What? No it doesn't

**Comment by xpple** [comment]
`Math.min`/`Math.max` is just an ternary if-statement, which would have to be called 6 times. The current code only uses three if statements by making use of the `else` clause.
Also, I don’t mind to change, we’re talking nanoseconds here.

**Comment by Earthcomputer** [comment]
The code is clearer though which is what really matters here. Also the JIT exists so it might not be 6 branches in practice

**Review by Earthcomputer — APPROVED** [review]
Ty!

**Pull request merged**
