### PR TITLE
Port to Mojmap

### PR DESCRIPTION
**Pull request by Gaming32**
This ports the entire mod to Mojmap, including renaming things that were named for Yarn things.

### CODE REVIEW

**Review by Earthcomputer — CHANGES_REQUESTED** [review]
Variables named after yarn need to be renamed

**Comment by Gaming32** [comment]
I did that though. Please let me know which ones I missed.

**Comment by Gaming32** [comment]
Alright, I've made a second pass through the codebase. Hopefully I got them all.

**Review by xpple — DISMISSED** [review]
Please revert the wildcard imports.

**Comment by Gaming32** [comment]
Using wildcard imports for static imports matches CONTRIBUTING.md.

**Comment by xpple** [comment]
Yes, but those need not be reverted as those weren't changed. I am referring to regular wildcard imports being removed in various places.

**Comment by Earthcomputer** [comment]
I think that's fine tbh, this PR changes almost every file anyway

**Comment by xpple** [comment]
Sure, but at least in `ClientCommands.java` then, that's too much in my opinion.

**Review by Earthcomputer — APPROVED** [review]

**Pull request merged**
