### PR TITLE
Add support for French

### PR DESCRIPTION
**Pull request by Starmania**
I skip some trads because the original is better than one in French, and I don't know how to translate some things.

I used **Json with comments**, and the construction passes, but I don't know if this is the right way to do it.

### CODE REVIEW

**Comment by xpple** [comment]
Thank you for your efforts! Could the comments be removed? I don't think they are very helpful, and more importantly I don't think the JSON parser Minecraft uses allows comments. Also, why are some lines translated but also commented out?

**Comment by Starmania** [comment]
I try in-game and the parser of Minecraft skip comments, so this is fine.

**Comment by Starmania** [comment]
And for some lines translated but commented, it's because the translation doesn't make sense (but I keep it for whoever wants to do it) or because I had no idea of a good translation.

**Comment by Starmania** [comment]
So, what I do, I remove comments yes or no ?

**Comment by Earthcomputer** [comment]
Yes please remove the comments. along with any translation that is still in English (I can see a few). The game will default to the English translation if there is no French one found.

**Comment by Starmania** [comment]
Ok, I edited files, they should be good

**Comment by Earthcomputer** [comment]
Any chance you could finish off the missing translations? If you want clarification on what they mean then just ask. If not then that's fine.

**Comment by Starmania** [comment]
Sorry, but I have no idea for a good traduction (and I'm native...)

**Pull request closed without merging**
