### PR TITLE
Allow validating open water for fishing bobbers

### PR DESCRIPTION
**Pull request by haykam821**
This pull request adds the `/cfish validate-open-water` subcommand, which determines if the player's current fishing bobber is considered to be in open water and thus able to fish up treasure.

### CODE REVIEW

**Comment by xpple** [comment]
Suggestion: 

* shorten the subcommand literal to `validate`
* shorten the feedback to _something shorter_

**Comment by haykam821** [comment]
If the intent is to have short subcommands, then the other ones should be renamed as well.

**Comment by xpple** [comment]
I mean - doesn't `validate` say enough?

**Comment by haykam821** [comment]
No, there are a lot of other things for fishing bobbers that can be validated.

**Comment by xpple** [comment]
Would those be nice additions as well? If so, a general `validate` subcommand would make sense to have

**Comment by Earthcomputer** [comment]
The problem with this check as implemented is that the fishing bobber not only needs to be in open water, but it needs to have always have been in open water from the moment it enters the water.

**Comment by haykam821** [comment]
Is that how open water works in vanilla? I had trouble understanding the decompiled logic.

The intent of the command is that one can verify the setup without having to re-cast the fishing rod each time. I can add a third case to distinguish between the position being considered open water in general or just open water for the current fishing bobber.

**Comment by Earthcomputer** [comment]
Yes that's how open water works in vanilla. If you look in `FishingManipulator` there is code there to simulate the fishing bobber before it's thrown, you could probably use that.

**Comment by haykam821** [comment]
Why would it need to be simulated? Shouldn't it only need to check the actual `inOpenWater` field of the fishing bobber?

**Comment by Earthcomputer** [comment]
Good point

**Comment by Earthcomputer** [comment]
This still needs to be changed to use the `inOpenWater` field.

**Comment by haykam821** [comment]
On 1.18.1, the client no longer updates `inOpenWater`. Would it be more trouble than it's worth to simulate the fishing bobber without fishing cracking? The message can still be changed to indicate that the fishing bobber must always be in open water for treasure.

**Comment by Earthcomputer** [comment]
Superseded by https://github.com/Earthcomputer/clientcommands/commit/6640836cee2243142a24cefe67c08f143eec6955

**Comment by haykam821** [comment]
This functionality would still be useful for validating open water in situations that do not involve fishing manipulation.

**Pull request closed without merging**
