### PR TITLE
✨Added Indonesian translate

### PR DESCRIPTION
**Pull request by barraIhsan**
Added Indonesian (`id_id.json`) translate

### CODE REVIEW

**Comment by Earthcomputer** [comment]
Hey, looks good so far, but I noticed there are a few remaining translations that are still in English. Any chance you could translate those too?

**Comment by barraIhsan** [comment]
Where exactly? Sometimes I don't translate them all because it's too formal, and actually a little bit hard to understand
For example "Enchantment" is supposed to be like "Sihir" or something, but its too formal

**Comment by xpple** [comment]
> Where exactly? Sometimes I don't translate them all because it's too formal, and actually a little bit hard to understand
> For example "Enchantment" is supposed to be like "Sihir" or something, but its too formal

image
I don't speak Indonesian at all so don't question me responding to this but I did find this (from https://crowdin.com/translate/minecraft/9435/enus-id)

**Comment by barraIhsan** [comment]
Good?

**Comment by barraIhsan** [comment]
Good?

**Review by Earthcomputer — APPROVED** [review]
Thank you!

**Pull request merged**
