### PR TITLE
Added 'things'

### PR DESCRIPTION
**Pull request by polarbub**
Please earth.

### CODE REVIEW

**Comment by Mhowser** [comment]
Can't you be more specific with what you added?
And if you have multiple features please split them up into separate pull requests.

**Comment by polarbub** [comment]
> Can't you be more specific with what you added?
> And if you have multiple features please split them up into separate pull requests.

https://github.com/Earthcomputer/clientcommands/pull/186/files line 101

**Comment by DragonEggBedrockBreaking** [comment]
I don't know how it looked to you, but to me it looked like they completely rewrote the file (GitHub error maybe?), so i put the text into a text comparer, and so here is the only change as far as I can see:
image

**Comment by Earthcomputer** [comment]
They changed the line endings. You can hide whitespace changes on github like this:
Screenshot from 2021-02-18 15-44-58
However if this weren't such a silly PR to be closed immediately, I'd have requested the line endings be fixed.

**Pull request closed without merging**
